name: Auto format

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  composer-normalize:
    name: Normalize composer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 8.1

      - name: Install composer normalize
        run: |
          composer global config allow-plugins.ergebnis/composer-normalize true
          composer global require ergebnis/composer-normalize --no-interaction

      - name: Run composer normalize
        run: composer normalize

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Normalize composer.json

  coding-style:
    name: Coding Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 8.1

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix code styling
